#ifndef _shell_commands_header_
#define _shell_commands_header_

#include "shell/echo/echo.h"
#include "shell/man/man.h"
#include "shell/help/help.h"
#include "shell/sudoku/sudoku.h"
#include "shell/unlink/unlink.h"
#include "shell/calc/calc.h"
#include "shell/getCPUSpeed/getCPUSpeed.h"
#include "shell/fortune/fortune.h"
#include "shell/date/date.h"
#include "shell/mkfifo/mkfifo.h"
#include "shell/kill/kill.h"
#include "shell/top/top.h"
#include "shell/cat/cat.h"
#include "shell/adduser/adduser.h"
#include "shell/users/users.h"
#include "shell/roflcopter/roflcopter.h"
#include "shell/wd/wd.h"
#include "shell/append/append.h"
#include "shell/userdel/userdel.h"
#include "shell/groupadd/groupadd.h"
#include "shell/groups/groups.h"
#include "shell/groupdel/groupdel.h"
#include "shell/passwd/passwd.h"
#include "shell/renice/renice.h"
#include "shell/busywait/busywait.h"
#include "shell/logout/logout.h"

#endif
